# validate_project.gd (SceneTree) - autogenerated for hard repair
extends SceneTree

func _init() -> void:
    call_deferred("_run_validation")

func _run_validation() -> void:
    var file_paths : Array = []
    var scan_dirs : Array = ["res://", "res://project", "res://project/assets"]
    for s in scan_dirs:
        _scan_recursive(s, file_paths)
    print("FOUND_FILES_COUNT: %s" % file_paths.size())
    for path in file_paths:
        print("\\n=== LOADING: %s ===" % path)
        var res = ResourceLoader.load(path)
        if res == null:
            print("LOAD_FAILED: %s" % path)
        else:
            if res is PackedScene:
                var inst = res.instantiate()
                if inst == null:
                    print("INSTANTIATE_FAILED: %s" % path)
        OS.delay_msec(10)
    print("\\nVALIDATION_COMPLETE")
    quit()

func _scan_recursive(base_path: String, file_paths: Array) -> void:
    var dir = DirAccess.open(base_path)
    if dir == null:
        return
    for f in dir.get_files():
        if f.ends_with(".tscn") or f.ends_with(".gd") or f.ends_with(".scn"):
            file_paths.append(base_path + "/" + f)
    for d in dir.get_directories():
        _scan_recursive(base_path + "/" + d, file_paths)
